# Generated by Django 3.1.2 on 2020-11-15 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('status', models.IntegerField(default=0)),
                ('feedback', models.CharField(blank=True, max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='sua.proof')),
                ('sua', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='sua.sua')),
            ],
        ),
    ]
