# Generated by Django 3.1.2 on 2020-11-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sua.activity'),
        ),
    ]
