# Generated by Django 3.1.2 on 2021-03-19 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0002_auto_20210316_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='sua.studentinfo'),
        ),
    ]
