# Generated by Django 3.1.2 on 2021-03-23 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sua', '0004_auto_20210319_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='proof_file',
        ),
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='classtype',
            field=models.CharField(default='一班', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='grade',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2021),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='phone',
            field=models.CharField(default='000', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proof',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to=settings.AUTH_USER_MODEL),
        ),
    ]
